stages: # List of stages for jobs, and their order of execution
  - build
  - lint
  - test

include:
  - local: 'pipelines/code_formatter.yml'
  - local: 'pipelines/build.yml'
  - local: 'pipelines/unit_test.yml'

